### ISSUE TITLE
i want to compile node-webkit on my board(arm a8)

### ISSUE THREAD

**Issue by youyudehexie** [toxygen/armhf-node-webkit#1]
i want to know What tutorials can refer

**Comment by toxygen** [comment]
have a look here https://gist.github.com/albi90/6135922
even though, i didn't follow that tutorial and made my own way. the problem is that the nature of issues you will run into varies from release to release. that being said, it's really not easy to get node-webkit to compile on arm. what board do you have?

**Comment by youyudehexie** [comment]
thanks , my board is cubieboard a10 
http://cubieboard.org/

**Comment by toxygen** [comment]
nice board. there seem to be a new howto: https://gist.github.com/albi90/6279255
